rm(list = ls())
library(dplyr)
library(haven)
library(readxl)
load("eh22.RData")
load("basefinal.RData")
file.choose()
as <- read_xlsx("C:\\UNIDAD\\MAESTRIA CIENCIA DE DATOS\\DATA_MININGIII\\DATAMIN\\trabajo_final\\trabajo\\codigo_caeb.xlsx",sheet = 1)
class(as)
eh22e %>% group_by(s08b_1) %>% summarise(n())
View(eh22p[,c(50:100)])
lista_caedec <- names(eh22p)
lista_caedec[1:5]
lista_caedec <- as.data.frame(lista_caedec)
attributes(eh22p$s01a_02)
levels(eh22p$s01a_02)
save(as,file = "basefinal.RData")
